import anthropic
import requests
import json
from datetime import datetime

TELEALERT_API = "http://localhost:5001"
MODEL = "claude-sonnet-4-6"

def get_current_metrics():
    """Fetch live metrics from TeleAlert API"""
    try:
        status = requests.get(f"{TELEALERT_API}/status").json()
        alerts = requests.get(f"{TELEALERT_API}/alerts").json()
        health = requests.get(f"{TELEALERT_API}/health").json()
        return {
            "health": health,
            "stats": status.get("stats", {}),
            "recent_critical_alerts": alerts.get("alerts", [])[:5],
            "timestamp": datetime.now().isoformat()
        }
    except Exception as e:
        return {"error": str(e)}

def diagnose_with_claude(metrics):
    """Send metrics to Claude for AI diagnosis"""
    client = anthropic.Anthropic()

    prompt = f"""You are a senior telecom NOC (Network Operations Centre) engineer 
at Bounteous × Telecom & Media Practice with 10 years of experience.

You are analyzing real-time metrics from TeleAlert — a telecom network 
event processing system running on Kubernetes.

Current system metrics:
{json.dumps(metrics, indent=2)}

Please provide:
1. SITUATION ASSESSMENT — What is happening on the network right now?
2. ROOT CAUSE ANALYSIS — What is likely causing this pattern?
3. SEVERITY LEVEL — Critical/High/Medium/Low and why
4. IMMEDIATE ACTION — Exact kubectl or system commands to run right now
5. PREVENTIVE MEASURES — What to do to prevent recurrence

Be specific, technical, and actionable. Format your response clearly."""

    message = client.messages.create(
        model=MODEL,
        max_tokens=1000,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    return message.content[0].text

def generate_incident_report(metrics, diagnosis):
    """Generate a formatted incident report"""
    report = f"""
╔══════════════════════════════════════════════════════════════╗
║           TELEALERT AI INCIDENT REPORT                       ║
║           Powered by Claude AI — Bounteous NOC               ║
╚══════════════════════════════════════════════════════════════╝

📅 Timestamp: {metrics.get('timestamp', 'N/A')}
🌐 Service:   {metrics.get('health', {}).get('service', 'N/A')}
📊 Version:   {metrics.get('health', {}).get('version', 'N/A')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📈 LIVE METRICS SNAPSHOT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Events:      {metrics.get('stats', {}).get('total_events', 0)}
Critical Alerts:   {metrics.get('stats', {}).get('critical_events', 0)}
Processed Events:  {metrics.get('stats', {}).get('processed_events', 0)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔴 RECENT CRITICAL ALERTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"""

    alerts = metrics.get('recent_critical_alerts', [])
    for alert in alerts:
        report += f"\n  [{alert[4]}] Node: {alert[1]} — {alert[3]}"

    report += f"""

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🤖 CLAUDE AI DIAGNOSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{diagnosis}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by TeleAlert AI Ops — Bounteous × Telecom & Media
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    return report

if __name__ == "__main__":
    print("🚀 TeleAlert AI Incident Response Bot starting...")
    print("📡 Fetching live metrics from TeleAlert API...")

    metrics = get_current_metrics()

    if "error" in metrics:
        print(f"❌ Error fetching metrics: {metrics['error']}")
        exit(1)

    print("🤖 Sending metrics to Claude for AI diagnosis...")
    print("⏳ Analyzing network patterns...\n")

    diagnosis = diagnose_with_claude(metrics)
    report = generate_incident_report(metrics, diagnosis)

    print(report)

    with open("/tmp/telealert_incident_report.txt", "w") as f:
        f.write(report)
    print("\n💾 Report saved to /tmp/telealert_incident_report.txt")