import anthropic
import requests
import json
import os
from datetime import datetime

client = anthropic.Anthropic(
    timeout=60.0,
    max_retries=3
)
MODEL = "claude-sonnet-4-6"
TELEALERT_API = "http://localhost:5001"

def get_historical_data():
    """Fetch current metrics and alerts as historical data"""
    try:
        status = requests.get(f"{TELEALERT_API}/status").json()
        alerts = requests.get(f"{TELEALERT_API}/alerts").json()
        return {
            "current_stats": status.get("stats", {}),
            "recent_alerts": alerts.get("alerts", []),
            "timestamp": datetime.now().isoformat()
        }
    except Exception as e:
        return {"error": str(e)}

def predict_with_claude(data):
    """Use Claude to predict future failures"""
    client_local = anthropic.Anthropic(
        timeout=60.0,
        max_retries=3
    )

    prompt = f"""You are a predictive analytics expert for 
telecom network operations at Bounteous × Telecom & Media Practice.

Analyze this network data and predict future failures:

Current Data:
{json.dumps(data, indent=2)}

Based on this data provide:

1. FAILURE PREDICTION
   - Which nodes are most likely to fail next?
   - Estimated time window for failure
   - Confidence percentage

2. PATTERN ANALYSIS
   - What patterns do you see in the alert data?
   - Are there recurring failure signatures?
   - What does the timing tell you?

3. RISK ASSESSMENT
   - High risk nodes (likely to fail in next hour)
   - Medium risk nodes (likely to fail in next 24h)
   - Low risk nodes (stable)

4. PREVENTIVE ACTIONS
   - Exact steps to prevent predicted failures
   - Which deployments to pre-scale
   - What to monitor closely

5. CONFIDENCE SCORE
   - Overall prediction confidence: X%
   - Data quality assessment
   - What additional data would improve predictions

Be specific with node names and timeframes."""

    message = client_local.messages.create(
        model=MODEL,
        max_tokens=1500,
        messages=[{
            "role": "user",
            "content": prompt
        }]
    )
    return message.content[0].text

def generate_prediction_report(data, prediction):
    """Generate formatted prediction report"""
    report = f"""
╔══════════════════════════════════════════════════════════════╗
║        TELEALERT PREDICTIVE ALERT SYSTEM                     ║
║        Powered by Claude AI — Bounteous NOC                  ║
╚══════════════════════════════════════════════════════════════╝

📅 Generated: {data.get('timestamp', 'N/A')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
📊 CURRENT NETWORK SNAPSHOT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Events:    {data.get('current_stats', {}).get('total_events', 0)}
Critical Events: {data.get('current_stats', {}).get('critical_events', 0)}
Processed:       {data.get('current_stats', {}).get('processed_events', 0)}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🔮 CLAUDE AI PREDICTIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{prediction}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by TeleAlert Predictive System — Bounteous NOC
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""
    return report

if __name__ == "__main__":
    print("🔮 TeleAlert Predictive Alert System starting...")
    print("📡 Fetching network data for analysis...")

    data = get_historical_data()

    if "error" in data:
        print(f"❌ Error: {data['error']}")
        exit(1)

    print("🤖 Claude is analyzing patterns and predicting failures...")
    print("⏳ Running predictive analysis...\n")

    prediction = predict_with_claude(data)
    report = generate_prediction_report(data, prediction)

    print(report)

    with open("/tmp/telealert_prediction_report.txt", "w") as f:
        f.write(report)
    print("💾 Report saved to /tmp/telealert_prediction_report.txt")