apiVersion: apps/v1
kind: Deployment
metadata:
  name: telealert-worker
  labels:
    app: telealert-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telealert-worker
  template:
    metadata:
      labels:
        app: telealert-worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/abhibounteous/telealert-worker@sha256:50b2a2c98bd5ca09efb884956c76fd5875044b875ab06d056477a626a41162e7
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: telealert
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: password