apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telealert-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:AbhiBounteous/telealert.git
    targetRevision: HEAD
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: telealert-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
